<a href="https://colab.research.google.com/github/mukulyadav0118/india-school-education-analytics/blob/main/01_data_inspection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import os
import pandas as pd
import numpy as np

print("India School Education Equity & Infrastructure Analytics")
print("Libraries imported successfully!")

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

India School Education Equity & Infrastructure Analytics
Libraries imported successfully!
Pandas version: 2.2.3
NumPy version: 2.1.3

In [ ]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

data_path = "/content/drive/MyDrive/ads prj/India_School_Education_Data"

for state in os.listdir(data_path):
    state_path = os.path.join(data_path, state)

    if os.path.isdir(state_path):
        print(f"\nState: {state}")
        print(os.listdir(state_path))

State: up
['extracted', 'profile_data_1_UTTAR PRADESH_2025-26.zip', 'enrolment_data_2_UTTAR PRADESH_2025-26.zip', 'facility_data_UTTAR PRADESH_2025-26.zip', 'teacher_data_UTTAR PRADESH_2025-26.zip']

State: chhattisgarh
['extracted', 'teacher_data_CHHATTISGARH_2025-26.zip', 'enrolment_data_2_CHHATTISGARH_2025-26.zip', 'facility_data_CHHATTISGARH_2025-26.zip', 'profile_data_1_CHHATTISGARH_2025-26.zip']

State: jharkhand
['extracted', 'profile_data_1_JHARKHAND_2025-26.zip', 'teacher_data_JHARKHAND_2025-26.zip', 'enrolment_data_2_JHARKHAND_2025-26.zip', 'facility_data_JHARKHAND_2025-26.zip']

State: mp
['extracted', 'teacher_data_MADHYA PRADESH_2025-26.zip', 'facility_data_MADHYA PRADESH_2025-26.zip', 'enrolment_data_2_MADHYA PRADESH_2025-26.zip', 'profile_data_1_MADHYA PRADESH_2025-26.zip']

State: bihar
['extracted', 'enrolment_data_2_BIHAR_2025-26.zip', 'facility_data_BIHAR_2025-26.zip', 'profile_data_1_BIHAR_2025-26.zip', 'teacher_data_BIHAR_2025-26.zip']

State: rajasthan
['enrolment_data_2_RAJASTHAN_2025-26.zip', 'facility_data_RAJASTHAN_2025-26.zip', 'teacher_data_RAJASTHAN_2025-26.zip', 'extracted', 'profile_data_1_RAJASTHAN_2025-26.zip']

State: haryana
['extracted', 'teacher_data_HARYANA_2025-26.zip', 'facility_data_HARYANA_2025-26.zip', 'profile_data_1_HARYANA_2025-26.zip', 'enrolment_data_2_HARYANA_2025-26.zip']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import os
import zipfile

data_path = "/content/drive/MyDrive/ads prj/India_School_Education_Data"

for state in os.listdir(data_path):
    state_path = os.path.join(data_path, state)

    if not os.path.isdir(state_path):
        continue

    extract_path = os.path.join(state_path, "extracted")
    os.makedirs(extract_path, exist_ok=True)

    for file in os.listdir(state_path):
        if file.endswith(".zip"):
            zip_path = os.path.join(state_path, file)

            with zipfile.ZipFile(zip_path, "r") as z:
                z.extractall(extract_path)

    print(f"Extracted datasets for {state}")

Extracted datasets for up
Extracted datasets for chhattisgarh
Extracted datasets for jharkhand
Extracted datasets for mp
Extracted datasets for bihar
Extracted datasets for rajasthan
Extracted datasets for haryana

In [ ]:
import os

for state in os.listdir(data_path):
    extract_path = os.path.join(data_path, state, "extracted")

    if os.path.isdir(extract_path):
        print(f"\n{state.upper()}")

        for root, dirs, files in os.walk(extract_path):
            for file in files:
                print(file)

UP
09_fac.csv
09_enr2.csv
09_tch.csv
09_prof1.csv

CHHATTISGARH
22_prof1.csv
22_enr2.csv
22_tch.csv
22_fac.csv

JHARKHAND
20_enr2.csv
20_prof1.csv
20_fac.csv
20_tch.csv

MP
23_prof1.csv
23_fac.csv
23_enr2.csv
23_tch.csv

BIHAR
10_prof1.csv
10_tch.csv
10_fac.csv
10_enr2.csv

RAJASTHAN
08_tch.csv
08_enr2.csv
08_prof1.csv
08_fac.csv

HARYANA
06_fac.csv
06_enr2.csv
06_tch.csv
06_prof1.csv

In [ ]:
data_path = "/content/drive/MyDrive/ads prj/India_School_Education_Data"

for state in os.listdir(data_path):
    extract_path = os.path.join(data_path, state, "extracted")

    if not os.path.isdir(extract_path):
        continue

    print(f"\n{'='*60}\nSTATE: {state.upper()}\n{'='*60}")

    for file in os.listdir(extract_path):
        if file.endswith(".csv"):
            file_path = os.path.join(extract_path, file)

            try:
                df = pd.read_csv(file_path, low_memory=False)

                print(f"\nFile: {file}")
                print("Rows and columns:", df.shape)
                print("Column names:")
                print(df.columns.tolist())
                print("First 3 rows:")
                display(df.head(3))

            except Exception as e:
                print(f"Could not read {file}: {e}")

============================================================
STATE: UP
============================================================

File: 09_fac.csv
Rows and columns: (265278, 82)
Column names:
['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
First 3 rows:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,4005762,3,1,1,1,3,9,3,0,0,...,1,9,9,9,9,9,9,300,300,1.0
1,3002509,1,1,1,1,8,8,8,0,0,...,2,9,9,9,9,9,9,0,0,NaN
2,3990241,2,1,1,1,5,0,5,0,0,...,1,9,9,9,9,9,9,0,0,NaN

File: 09_enr2.csv
Rows and columns: (2491171, 42)
Column names:
['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
First 3 rows:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000070,8,5,0,0,0,5,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000070,8,6,0,0,0,3,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1000070,8,7,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0

File: 09_tch.csv
Rows and columns: (265278, 38)
Column names:
['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
First 3 rows:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000070,5,3,2,0,1,1,0,3,3,...,1,0,2,0,0,0,0,0,0,5
1,1000096,2,2,0,0,2,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
2,1000102,3,0,3,0,0,0,1,2,2,...,1,0,0,1,0,0,1,0,0,0

File: 09_prof1.csv
Rows and columns: (265278, 49)
Column names:
['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
First 3 rows:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,6071678,UTTAR PRADESH,GAUTAM BUDDHA NAGAR,VISRAKH,1,NaN,NaN,NaN,NaN,Chougain,...,9,1993,9,2,1,2,9,0,0,9
1,4005762,UTTAR PRADESH,RAE BARELI,CHHATOH,1,NaN,NaN,Chhatoh,Chhatoh,Chhatoh,...,9,2007,2,2,1,1,1,7,100,2
2,3782350,UTTAR PRADESH,BAREILLY,NAWABGANJ,1,NaN,NaN,Duawawat,Duawawat,Nawabganj,...,9,1998,2,2,9,2,1,10,0,2

============================================================
STATE: CHHATTISGARH
============================================================

File: 22_prof1.csv
Rows and columns: (57036, 49)
Column names:
['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
First 3 rows:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,3436595,CHHATTISGARH,KONDAGAON,BADERAJPUR,1,NaN,NaN,Hatma,Hatma,Baderajpur,...,9,1958,1,2,9,2,2,0,0,1
1,4611143,CHHATTISGARH,SURAJPUR,SURAJPUR,1,NaN,NaN,Sapkara,Sapkara,Surajpur,...,9,1958,1,2,9,2,2,0,0,1
2,7799856,CHHATTISGARH,KONDAGAON,PHARASGAON,1,NaN,NaN,Patoda,Patoda,Pharasgaon,...,9,1973,2,2,9,2,1,5,0,1

File: 22_enr2.csv
Rows and columns: (421820, 42)
Column names:
['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
First 3 rows:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000021,8,5,0,0,0,6,4,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000021,8,6,0,0,0,1,2,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1000021,8,7,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0

File: 22_tch.csv
Rows and columns: (57036, 38)
Column names:
['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
First 3 rows:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000021,3,1,2,0,0,1,0,2,3,...,0,0,0,0,0,0,0,1,0,1
1,1000048,4,4,0,0,0,0,4,0,4,...,0,0,0,1,0,0,2,0,0,0
2,1000331,4,4,0,0,0,1,1,2,4,...,1,0,0,0,0,0,0,0,0,1

File: 22_fac.csv
Rows and columns: (57036, 82)
Column names:
['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
First 3 rows:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,4924069,3,3,3,2,6,0,3,0,3,...,1,9,9,2,9,9,9,0,0,1.0
1,3436595,3,5,5,7,5,0,5,0,0,...,1,9,9,2,9,9,9,0,0,1.0
2,3606585,3,3,3,2,6,4,0,6,0,...,2,2,2,9,9,2,2,0,0,1.0

============================================================
STATE: JHARKHAND
============================================================

File: 20_enr2.csv
Rows and columns: (433493, 42)
Column names:
['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
First 3 rows:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000233,8,5,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000233,8,6,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1000233,8,7,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0

File: 20_prof1.csv
Rows and columns: (44378, 49)
Column names:
['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
First 3 rows:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,6996689,JHARKHAND,RAMGARH,DULMI,1,NaN,NaN,Priyatu,Siru,Dulmi,...,9,1962,1,2,9,2,1,4,0,1
1,9214686,JHARKHAND,RANCHI,ANGARA,1,NaN,NaN,Angara,Angara,Angara,...,9,2006,2,2,9,2,2,0,0,2
2,9773614,JHARKHAND,Sahebganj,PATHNA,1,NaN,NaN,Amgachhi,Kendua,Pathna,...,9,2003,1,2,9,2,1,3,0,1

File: 20_fac.csv
Rows and columns: (44378, 82)
Column names:
['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
First 3 rows:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,6773797,3,1,1,5,3,1,2,1,0,...,2,9,9,2,9,9,9,0,0,1.0
1,9214686,3,3,3,6,3,0,3,0,0,...,2,9,9,2,9,9,9,0,0,2.0
2,9525194,3,2,2,1,7,7,5,0,2,...,1,9,9,2,9,9,9,0,0,1.0

File: 20_tch.csv
Rows and columns: (44378, 38)
Column names:
['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
First 3 rows:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000233,2,1,1,0,0,1,0,1,1,...,0,0,2,0,0,0,0,0,0,0
1,1000320,2,1,1,0,0,0,1,1,1,...,0,0,1,0,0,0,0,1,0,0
2,1000390,2,1,1,0,0,0,1,1,0,...,0,0,1,0,0,0,0,0,0,0

============================================================
STATE: MP
============================================================

File: 23_prof1.csv
Rows and columns: (119694, 49)
Column names:
['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
First 3 rows:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,6437918,MADHYA PRADESH,KHANDWA,PANDHANA,1,NaN,NaN,Pangra,Pangra,Pandhana,...,9,2003,2,2,9,2,1,0,0,1
1,1622854,MADHYA PRADESH,ASHOKNAGAR,ASHOKNAGAR,1,NaN,NaN,Menai,Menai,Ashoknagar,...,9,2000,2,2,2,2,2,0,0,1
2,5688946,MADHYA PRADESH,INDORE,INDORE URBAN-2,2,Indore-Municipal Corporations,Khajaraana,NaN,NaN,NaN,...,9,2024,9,2,9,2,9,0,0,9

File: 23_fac.csv
Rows and columns: (119694, 82)
Column names:
['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
First 3 rows:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,3430331,3,1,1,5,3,0,1,2,0,...,2,9,9,2,9,9,9,0,0,1.0
1,5945458,3,3,3,1,3,0,1,1,1,...,2,9,9,2,9,9,9,0,0,1.0
2,3179225,3,1,1,1,1,0,1,0,0,...,2,9,9,2,9,9,9,0,0,1.0

File: 23_enr2.csv
Rows and columns: (1078230, 42)
Column names:
['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
First 3 rows:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000089,8,3,6,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000089,8,4,6,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1000089,8,5,4,2,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

File: 23_tch.csv
Rows and columns: (119694, 38)
Column names:
['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
First 3 rows:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000089,6,2,4,0,2,0,0,4,6,...,1,0,0,1,0,0,2,0,0,0
1,1000149,2,1,1,0,1,0,0,1,1,...,0,0,0,0,0,0,1,0,0,0
2,1000453,12,0,12,0,9,1,0,2,12,...,4,0,0,3,1,0,4,0,0,0

============================================================
STATE: BIHAR
============================================================

File: 10_prof1.csv
Rows and columns: (95285, 49)
Column names:
['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
First 3 rows:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,7626939,BIHAR,ROHTAS,TILOUTHU,1,NaN,NaN,Chorkap,Chandanpura,Tilouthu,...,9,1985,2,2,9,2,1,4,0,2
1,4739232,BIHAR,MADHUBANI,MADHEPUR,1,NaN,NaN,Sundar Birajit,Sundar Birajeet,Madhepur,...,9,1973,2,2,9,2,2,0,0,2
2,2400767,BIHAR,DARBHANGA,GHANSHYAMPUR,1,NaN,NaN,NaN,NaN,Ghanshyampur,...,9,1973,9,2,2,1,9,0,0,9

File: 10_tch.csv
Rows and columns: (95285, 38)
Column names:
['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
First 3 rows:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000031,13,9,4,0,4,1,0,8,13,...,4,1,1,3,1,0,0,0,0,0
1,1000035,8,6,2,0,2,2,0,4,8,...,7,1,0,0,0,0,0,0,0,0
2,1000049,4,1,3,0,0,0,0,4,4,...,0,0,0,0,0,0,0,0,0,0

File: 10_fac.csv
Rows and columns: (95285, 82)
Column names:
['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
First 3 rows:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,6459768,3,3,3,1,8,0,5,3,0,...,2,9,9,2,9,9,9,0,0,1.0
1,6772401,3,2,2,1,8,0,4,4,0,...,2,9,9,2,9,9,9,0,0,1.0
2,7863767,4,1,1,1,1,0,1,0,0,...,2,9,9,2,9,9,9,0,0,1.0

File: 10_enr2.csv
Rows and columns: (972166, 42)
Column names:
['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
First 3 rows:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000031,8,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000031,8,5,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1000031,8,6,0,0,0,4,7,0,0,...,0,0,0,0,0,0,0,0,0,0

============================================================
STATE: RAJASTHAN
============================================================

File: 08_tch.csv
Rows and columns: (106445, 38)
Column names:
['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
First 3 rows:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000032,2,1,1,0,0,1,0,1,2,...,0,0,0,0,0,0,0,0,0,0
1,1000150,3,1,2,0,0,1,0,2,2,...,1,0,0,2,0,0,0,0,0,0
2,1000199,4,4,0,0,0,2,0,2,4,...,0,0,1,3,0,0,0,0,0,0

File: 08_enr2.csv
Rows and columns: (1084857, 42)
Column names:
['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
First 3 rows:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000032,8,4,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000032,8,5,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1000032,8,6,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

File: 08_prof1.csv
Rows and columns: (106445, 49)
Column names:
['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
First 3 rows:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,8131457,RAJASTHAN,PHALODI,BAPINI,1,NaN,NaN,Motaniya Nagar,Motaniya Nagar,Bapini,...,9,1999,1,2,9,2,1,0,0,2
1,4842002,RAJASTHAN,BALOTRA,GIDA,1,NaN,NaN,Kharthoniyon Ka Tala,Kanor,Gira,...,9,1995,1,2,2,2,1,2,0,1
2,4718146,RAJASTHAN,PRATAPGARH,PRATAPGARH,1,NaN,NaN,Awleshwar,Awleshwar,Pratapgarh,...,9,1932,1,1,2,2,1,4,0,1

File: 08_fac.csv
Rows and columns: (106445, 82)
Column names:
['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
First 3 rows:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,3131252,3,1,1,6,2,1,2,0,0,...,2,9,9,2,9,9,9,0,0,1.0
1,5085949,3,1,1,1,3,3,1,0,2,...,2,9,9,2,9,9,9,0,0,1.0
2,4842002,3,1,1,3,5,5,5,0,0,...,2,9,9,2,9,9,9,111,0,1.0

============================================================
STATE: HARYANA
============================================================

File: 06_fac.csv
Rows and columns: (23479, 82)
Column names:
['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
First 3 rows:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,3866044,3,1,1,1,6,2,3,3,0,...,1,9,9,2,9,9,9,0,0,1.0
1,5253916,3,7,7,1,11,8,4,7,0,...,1,2,2,9,9,2,2,171,171,1.0
2,4592997,3,1,1,1,14,7,7,4,3,...,1,2,2,9,9,2,2,653,653,1.0

File: 06_enr2.csv
Rows and columns: (240115, 42)
Column names:
['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
First 3 rows:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000040,8,4,0,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000040,8,5,4,1,0,5,5,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1000040,8,6,1,0,0,3,8,0,6,...,0,0,0,0,0,0,0,0,0,0

File: 06_tch.csv
Rows and columns: (23479, 38)
Column names:
['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
First 3 rows:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000040,13,5,8,0,6,3,0,4,2,...,4,0,3,3,0,0,1,0,0,0
1,1001720,16,6,10,0,8,0,0,8,0,...,11,0,0,1,0,0,0,0,0,0
2,1002230,5,0,5,0,4,0,0,1,0,...,3,0,1,0,0,0,1,0,0,0

File: 06_prof1.csv
Rows and columns: (23479, 49)
Column names:
['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
First 3 rows:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,5864327,HARYANA,NUH,PUNHANA,1,NaN,NaN,Hathan Gaon(227),Hathangaon,Punahana,...,9,1954,1,2,9,2,1,9,0,1
1,9234276,HARYANA,YAMUNANAGAR,CHHACHHRAULI,1,NaN,NaN,Chhachhrauli (311),Chhachhrauli,Chhachhrauli,...,9,1960,2,2,9,2,2,0,0,2
2,1753236,HARYANA,JIND,SAFIDON,1,NaN,NaN,Jaipur (24),Jaipur,Safidon,...,9,1956,2,2,9,2,1,10,0,1

In [ ]:
import os
import pandas as pd

data_path = "/content/drive/MyDrive/ads prj/India_School_Education_Data"

for state in os.listdir(data_path):
    extracted_path = os.path.join(data_path, state, "extracted")

    if not os.path.isdir(extracted_path):
        continue

    print(f"\n{'='*60}\nSTATE: {state}\n{'='*60}")

    for root, dirs, files in os.walk(extracted_path):
        for file in files:
            if file.endswith(".csv"):
                file_path = os.path.join(root, file)

                try:
                    df = pd.read_csv(file_path, low_memory=False)

                    print(f"\nFile: {file}")
                    print("Rows and columns:", df.shape)
                    print("Column names:", df.columns.tolist())
                    print("Data types:")
                    print(df.dtypes.to_string())
                    print("Sample:")
                    display(df.head(3))

                except Exception as e:
                    print(f"Could not read {file}: {e}")

============================================================
STATE: up
============================================================

File: 09_fac.csv
Rows and columns: (265278, 82)
Column names: ['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
Data types:
pseudocode                         int64
building_status                    int64
no_building_blocks                 int64
pucca_building_blocks              int64
boundary_wall                      int64
total_class_rooms                  int64
other_rooms                        int64
classrooms_in_good_condition       int64
classrooms_needs_minor_repair      int64
classrooms_needs_major_repair      int64
separate_room_for_hm               int64
total_boys_toilet                  int64
total_boys_func_toilet             int64
total_girls_toilet                 int64
total_girls_func_toilet            int64
total_boys_cwsn_toilet             int64
func_boys_cwsn_friendly            int64
total_girls_cwsn_toilet            int64
func_girls_cwsn_friendly           int64
urinal_boys                        int64
urinal_girls                       int64
handwash_near_toilet               int64
hand_pump_yn                       int64
well_prot_yn                       int64
tap_yn                             int64
othsrc_yn                          int64
well_unprot_yn                     int64
pack_water_yn                      int64
hand_pump_fun_yn                   int64
well_prot_fun_yn                   int64
tap_fun_yn                         int64
othsrc_fun_yn                      int64
well_unprot_fun_yn                 int64
pack_water_fun_yn                  int64
rain_water_harvesting              int64
handwash_facility_for_meal         int64
electricity_availability           int64
solar_panel                        int64
library_availability               int64
book_bank                          int64
reading_corner                     int64
playground_available               int64
playground_alt_yn                  int64
medical_checkups                   int64
availability_ramps                 int64
availability_of_handrails          int64
furniture_availability             int64
phy_lab_cond                       int64
chem_lab_cond                      int64
bio_lab_cond                       int64
math_lab_cond                      int64
lang_lab_cond                      int64
geo_lab_cond                       int64
home_sc_lab_cond                   int64
psycho_lab_cond                    int64
comp_lab_cond                      int64
comp_ict_lab_yn                    int64
ict_lab_yn                         int64
laptop                             int64
tablet                             int64
desktop                            int64
digiboard                          int64
teachdev_tot                       int64
server_tot                         int64
smart_class_tv_tot                 int64
projector                          int64
printer                            int64
internet                           int64
dth                                int64
spl_educator_yn                    int64
librarian_yn                       int64
land_avl_yn                        int64
kitchen_garden_yn                  int64
staff_qtr_yn                       int64
tinkering_lab_yn                   int64
boarding_pri_yn                    int64
boarding_upr_yn                    int64
boarding_sec_yn                    int64
boarding_hsec_yn                   int64
cyber_safety                       int64
psycho_social                      int64
enrichment_activities            float64
Sample:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,4005762,3,1,1,1,3,9,3,0,0,...,1,9,9,9,9,9,9,300,300,1.0
1,3002509,1,1,1,1,8,8,8,0,0,...,2,9,9,9,9,9,9,0,0,NaN
2,3990241,2,1,1,1,5,0,5,0,0,...,1,9,9,9,9,9,9,0,0,NaN

File: 09_enr2.csv
Rows and columns: (2491171, 42)
Column names: ['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
Data types:
pseudocode    int64
item_group    int64
item_id       int64
cpp_b         int64
cpp_g         int64
cpp_t         int64
c1_b          int64
c1_g          int64
c1_t          int64
c2_b          int64
c2_g          int64
c2_t          int64
c3_b          int64
c3_g          int64
c3_t          int64
c4_b          int64
c4_g          int64
c4_t          int64
c5_b          int64
c5_g          int64
c5_t          int64
c6_b          int64
c6_g          int64
c6_t          int64
c7_b          int64
c7_g          int64
c7_t          int64
c8_b          int64
c8_g          int64
c8_t          int64
c9_b          int64
c9_g          int64
c9_t          int64
c10_b         int64
c10_g         int64
c10_t         int64
c11_b         int64
c11_g         int64
c11_t         int64
c12_b         int64
c12_g         int64
c12_t         int64
Sample:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000070,8,5,0,0,0,5,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000070,8,6,0,0,0,3,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1000070,8,7,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0

File: 09_tch.csv
Rows and columns: (265278, 38)
Column names: ['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
Data types:
pseudocode                                 int64
total_tch                                  int64
male                                       int64
female                                     int64
transgender                                int64
gen_tch                                    int64
sc_tch                                     int64
st_tch                                     int64
obc_tch                                    int64
regular                                    int64
contract                                   int64
part_time                                  int64
below_graduate                             int64
graduate                                   int64
post_graduate_and_above                    int64
trained_comp                               int64
class_taught_pr                            int64
class_taught_upr                           int64
class_taught_pr_upr                        int64
class_taught_sec_only                      int64
class_taught_hsec_only                     int64
class_taught_upr_sec                       int64
class_taught_sec_hsec                      int64
class_taugt_pre_primary_only               int64
class_taught_pr_and_pre_pri                int64
teacher_involve_non_training_assignment    int64
diploma_certificate                        int64
bachelor_of_ee                             int64
bed_equivalent                             int64
med_equivalent                             int64
other                                      int64
none                                       int64
diploma_special_edu                        int64
pursuing_rpc                               int64
diploma_ele_edu                            int64
early_childhood_tch                        int64
bed_nursery                                int64
trained_cwsn                               int64
Sample:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000070,5,3,2,0,1,1,0,3,3,...,1,0,2,0,0,0,0,0,0,5
1,1000096,2,2,0,0,2,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
2,1000102,3,0,3,0,0,0,1,2,2,...,1,0,0,1,0,0,1,0,0,0

File: 09_prof1.csv
Rows and columns: (265278, 49)
Column names: ['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
Data types:
pseudocode                      int64
state                          object
district                       object
block                          object
rural_urban                     int64
lgd_urban_local_body_name      object
lgd_ward_name                  object
lgd_vill_name                  object
lgd_vill_panchayat_name        object
lgd_block_name                 object
school_category                 int64
school_type                     int64
lowclass                        int64
highclass                       int64
managment                       int64
pincode                         int64
special_school_for_cwsn         int64
shift_school                    int64
resi_school                     int64
resi_type                       int64
minority_school                 int64
medium_instr1                   int64
medium_of_instr2                int64
medium_of_instr3                int64
medium_of_instr4                int64
aff_board_sec                   int64
aff_board_hsec                  int64
approachable_road               int64
pre_primary                     int64
anganwadi_yn                    int64
avg_instr_days                  int64
cce_yn                          int64
same_sch_b                      int64
same_sch_g                      int64
other_sch_b                     int64
other_sch_g                     int64
anganwadi_ecce_b                int64
anganwadi_ecce_g                int64
cwsn_sch_type                   int64
rte_25p_admission_yn            int64
estd_year                       int64
certified_fit_india_yn          int64
is_nsqf                         int64
prevoc_yn                       int64
stc_yn                          int64
smdc_pta_yn                     int64
smdc_pta_meeting                int64
remedial_tch_enrol              int64
learner_holistic_rptcard_yn     int64
Sample:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,6071678,UTTAR PRADESH,GAUTAM BUDDHA NAGAR,VISRAKH,1,NaN,NaN,NaN,NaN,Chougain,...,9,1993,9,2,1,2,9,0,0,9
1,4005762,UTTAR PRADESH,RAE BARELI,CHHATOH,1,NaN,NaN,Chhatoh,Chhatoh,Chhatoh,...,9,2007,2,2,1,1,1,7,100,2
2,3782350,UTTAR PRADESH,BAREILLY,NAWABGANJ,1,NaN,NaN,Duawawat,Duawawat,Nawabganj,...,9,1998,2,2,9,2,1,10,0,2

============================================================
STATE: chhattisgarh
============================================================

File: 22_prof1.csv
Rows and columns: (57036, 49)
Column names: ['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
Data types:
pseudocode                      int64
state                          object
district                       object
block                          object
rural_urban                     int64
lgd_urban_local_body_name      object
lgd_ward_name                  object
lgd_vill_name                  object
lgd_vill_panchayat_name        object
lgd_block_name                 object
school_category                 int64
school_type                     int64
lowclass                        int64
highclass                       int64
managment                       int64
pincode                         int64
special_school_for_cwsn         int64
shift_school                    int64
resi_school                     int64
resi_type                       int64
minority_school                 int64
medium_instr1                   int64
medium_of_instr2                int64
medium_of_instr3                int64
medium_of_instr4                int64
aff_board_sec                   int64
aff_board_hsec                  int64
approachable_road               int64
pre_primary                     int64
anganwadi_yn                    int64
avg_instr_days                  int64
cce_yn                          int64
same_sch_b                      int64
same_sch_g                      int64
other_sch_b                     int64
other_sch_g                     int64
anganwadi_ecce_b                int64
anganwadi_ecce_g                int64
cwsn_sch_type                   int64
rte_25p_admission_yn            int64
estd_year                       int64
certified_fit_india_yn          int64
is_nsqf                         int64
prevoc_yn                       int64
stc_yn                          int64
smdc_pta_yn                     int64
smdc_pta_meeting                int64
remedial_tch_enrol              int64
learner_holistic_rptcard_yn     int64
Sample:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,3436595,CHHATTISGARH,KONDAGAON,BADERAJPUR,1,NaN,NaN,Hatma,Hatma,Baderajpur,...,9,1958,1,2,9,2,2,0,0,1
1,4611143,CHHATTISGARH,SURAJPUR,SURAJPUR,1,NaN,NaN,Sapkara,Sapkara,Surajpur,...,9,1958,1,2,9,2,2,0,0,1
2,7799856,CHHATTISGARH,KONDAGAON,PHARASGAON,1,NaN,NaN,Patoda,Patoda,Pharasgaon,...,9,1973,2,2,9,2,1,5,0,1

File: 22_enr2.csv
Rows and columns: (421820, 42)
Column names: ['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
Data types:
pseudocode    int64
item_group    int64
item_id       int64
cpp_b         int64
cpp_g         int64
cpp_t         int64
c1_b          int64
c1_g          int64
c1_t          int64
c2_b          int64
c2_g          int64
c2_t          int64
c3_b          int64
c3_g          int64
c3_t          int64
c4_b          int64
c4_g          int64
c4_t          int64
c5_b          int64
c5_g          int64
c5_t          int64
c6_b          int64
c6_g          int64
c6_t          int64
c7_b          int64
c7_g          int64
c7_t          int64
c8_b          int64
c8_g          int64
c8_t          int64
c9_b          int64
c9_g          int64
c9_t          int64
c10_b         int64
c10_g         int64
c10_t         int64
c11_b         int64
c11_g         int64
c11_t         int64
c12_b         int64
c12_g         int64
c12_t         int64
Sample:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000021,8,5,0,0,0,6,4,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000021,8,6,0,0,0,1,2,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1000021,8,7,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0

File: 22_tch.csv
Rows and columns: (57036, 38)
Column names: ['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
Data types:
pseudocode                                 int64
total_tch                                  int64
male                                       int64
female                                     int64
transgender                                int64
gen_tch                                    int64
sc_tch                                     int64
st_tch                                     int64
obc_tch                                    int64
regular                                    int64
contract                                   int64
part_time                                  int64
below_graduate                             int64
graduate                                   int64
post_graduate_and_above                    int64
trained_comp                               int64
class_taught_pr                            int64
class_taught_upr                           int64
class_taught_pr_upr                        int64
class_taught_sec_only                      int64
class_taught_hsec_only                     int64
class_taught_upr_sec                       int64
class_taught_sec_hsec                      int64
class_taugt_pre_primary_only               int64
class_taught_pr_and_pre_pri                int64
teacher_involve_non_training_assignment    int64
diploma_certificate                        int64
bachelor_of_ee                             int64
bed_equivalent                             int64
med_equivalent                             int64
other                                      int64
none                                       int64
diploma_special_edu                        int64
pursuing_rpc                               int64
diploma_ele_edu                            int64
early_childhood_tch                        int64
bed_nursery                                int64
trained_cwsn                               int64
Sample:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000021,3,1,2,0,0,1,0,2,3,...,0,0,0,0,0,0,0,1,0,1
1,1000048,4,4,0,0,0,0,4,0,4,...,0,0,0,1,0,0,2,0,0,0
2,1000331,4,4,0,0,0,1,1,2,4,...,1,0,0,0,0,0,0,0,0,1

File: 22_fac.csv
Rows and columns: (57036, 82)
Column names: ['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
Data types:
pseudocode                         int64
building_status                    int64
no_building_blocks                 int64
pucca_building_blocks              int64
boundary_wall                      int64
total_class_rooms                  int64
other_rooms                        int64
classrooms_in_good_condition       int64
classrooms_needs_minor_repair      int64
classrooms_needs_major_repair      int64
separate_room_for_hm               int64
total_boys_toilet                  int64
total_boys_func_toilet             int64
total_girls_toilet                 int64
total_girls_func_toilet            int64
total_boys_cwsn_toilet             int64
func_boys_cwsn_friendly            int64
total_girls_cwsn_toilet            int64
func_girls_cwsn_friendly           int64
urinal_boys                        int64
urinal_girls                       int64
handwash_near_toilet               int64
hand_pump_yn                       int64
well_prot_yn                       int64
tap_yn                             int64
othsrc_yn                          int64
well_unprot_yn                     int64
pack_water_yn                      int64
hand_pump_fun_yn                   int64
well_prot_fun_yn                   int64
tap_fun_yn                         int64
othsrc_fun_yn                      int64
well_unprot_fun_yn                 int64
pack_water_fun_yn                  int64
rain_water_harvesting              int64
handwash_facility_for_meal         int64
electricity_availability           int64
solar_panel                        int64
library_availability               int64
book_bank                          int64
reading_corner                     int64
playground_available               int64
playground_alt_yn                  int64
medical_checkups                   int64
availability_ramps                 int64
availability_of_handrails          int64
furniture_availability             int64
phy_lab_cond                       int64
chem_lab_cond                      int64
bio_lab_cond                       int64
math_lab_cond                      int64
lang_lab_cond                      int64
geo_lab_cond                       int64
home_sc_lab_cond                   int64
psycho_lab_cond                    int64
comp_lab_cond                      int64
comp_ict_lab_yn                    int64
ict_lab_yn                         int64
laptop                             int64
tablet                             int64
desktop                            int64
digiboard                          int64
teachdev_tot                       int64
server_tot                         int64
smart_class_tv_tot                 int64
projector                          int64
printer                            int64
internet                           int64
dth                                int64
spl_educator_yn                    int64
librarian_yn                       int64
land_avl_yn                        int64
kitchen_garden_yn                  int64
staff_qtr_yn                       int64
tinkering_lab_yn                   int64
boarding_pri_yn                    int64
boarding_upr_yn                    int64
boarding_sec_yn                    int64
boarding_hsec_yn                   int64
cyber_safety                       int64
psycho_social                      int64
enrichment_activities            float64
Sample:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,4924069,3,3,3,2,6,0,3,0,3,...,1,9,9,2,9,9,9,0,0,1.0
1,3436595,3,5,5,7,5,0,5,0,0,...,1,9,9,2,9,9,9,0,0,1.0
2,3606585,3,3,3,2,6,4,0,6,0,...,2,2,2,9,9,2,2,0,0,1.0

============================================================
STATE: jharkhand
============================================================

File: 20_enr2.csv
Rows and columns: (433493, 42)
Column names: ['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
Data types:
pseudocode    int64
item_group    int64
item_id       int64
cpp_b         int64
cpp_g         int64
cpp_t         int64
c1_b          int64
c1_g          int64
c1_t          int64
c2_b          int64
c2_g          int64
c2_t          int64
c3_b          int64
c3_g          int64
c3_t          int64
c4_b          int64
c4_g          int64
c4_t          int64
c5_b          int64
c5_g          int64
c5_t          int64
c6_b          int64
c6_g          int64
c6_t          int64
c7_b          int64
c7_g          int64
c7_t          int64
c8_b          int64
c8_g          int64
c8_t          int64
c9_b          int64
c9_g          int64
c9_t          int64
c10_b         int64
c10_g         int64
c10_t         int64
c11_b         int64
c11_g         int64
c11_t         int64
c12_b         int64
c12_g         int64
c12_t         int64
Sample:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000233,8,5,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000233,8,6,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1000233,8,7,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0

File: 20_prof1.csv
Rows and columns: (44378, 49)
Column names: ['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
Data types:
pseudocode                      int64
state                          object
district                       object
block                          object
rural_urban                     int64
lgd_urban_local_body_name      object
lgd_ward_name                  object
lgd_vill_name                  object
lgd_vill_panchayat_name        object
lgd_block_name                 object
school_category                 int64
school_type                     int64
lowclass                        int64
highclass                       int64
managment                       int64
pincode                         int64
special_school_for_cwsn         int64
shift_school                    int64
resi_school                     int64
resi_type                       int64
minority_school                 int64
medium_instr1                   int64
medium_of_instr2                int64
medium_of_instr3                int64
medium_of_instr4                int64
aff_board_sec                   int64
aff_board_hsec                  int64
approachable_road               int64
pre_primary                     int64
anganwadi_yn                    int64
avg_instr_days                  int64
cce_yn                          int64
same_sch_b                      int64
same_sch_g                      int64
other_sch_b                     int64
other_sch_g                     int64
anganwadi_ecce_b                int64
anganwadi_ecce_g                int64
cwsn_sch_type                   int64
rte_25p_admission_yn            int64
estd_year                       int64
certified_fit_india_yn          int64
is_nsqf                         int64
prevoc_yn                       int64
stc_yn                          int64
smdc_pta_yn                     int64
smdc_pta_meeting                int64
remedial_tch_enrol              int64
learner_holistic_rptcard_yn     int64
Sample:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,6996689,JHARKHAND,RAMGARH,DULMI,1,NaN,NaN,Priyatu,Siru,Dulmi,...,9,1962,1,2,9,2,1,4,0,1
1,9214686,JHARKHAND,RANCHI,ANGARA,1,NaN,NaN,Angara,Angara,Angara,...,9,2006,2,2,9,2,2,0,0,2
2,9773614,JHARKHAND,Sahebganj,PATHNA,1,NaN,NaN,Amgachhi,Kendua,Pathna,...,9,2003,1,2,9,2,1,3,0,1

File: 20_fac.csv
Rows and columns: (44378, 82)
Column names: ['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
Data types:
pseudocode                         int64
building_status                    int64
no_building_blocks                 int64
pucca_building_blocks              int64
boundary_wall                      int64
total_class_rooms                  int64
other_rooms                        int64
classrooms_in_good_condition       int64
classrooms_needs_minor_repair      int64
classrooms_needs_major_repair      int64
separate_room_for_hm               int64
total_boys_toilet                  int64
total_boys_func_toilet             int64
total_girls_toilet                 int64
total_girls_func_toilet            int64
total_boys_cwsn_toilet             int64
func_boys_cwsn_friendly            int64
total_girls_cwsn_toilet            int64
func_girls_cwsn_friendly           int64
urinal_boys                        int64
urinal_girls                       int64
handwash_near_toilet               int64
hand_pump_yn                       int64
well_prot_yn                       int64
tap_yn                             int64
othsrc_yn                          int64
well_unprot_yn                     int64
pack_water_yn                      int64
hand_pump_fun_yn                   int64
well_prot_fun_yn                   int64
tap_fun_yn                         int64
othsrc_fun_yn                      int64
well_unprot_fun_yn                 int64
pack_water_fun_yn                  int64
rain_water_harvesting              int64
handwash_facility_for_meal         int64
electricity_availability           int64
solar_panel                        int64
library_availability               int64
book_bank                          int64
reading_corner                     int64
playground_available               int64
playground_alt_yn                  int64
medical_checkups                   int64
availability_ramps                 int64
availability_of_handrails          int64
furniture_availability             int64
phy_lab_cond                       int64
chem_lab_cond                      int64
bio_lab_cond                       int64
math_lab_cond                      int64
lang_lab_cond                      int64
geo_lab_cond                       int64
home_sc_lab_cond                   int64
psycho_lab_cond                    int64
comp_lab_cond                      int64
comp_ict_lab_yn                    int64
ict_lab_yn                         int64
laptop                             int64
tablet                             int64
desktop                            int64
digiboard                          int64
teachdev_tot                       int64
server_tot                         int64
smart_class_tv_tot                 int64
projector                          int64
printer                            int64
internet                           int64
dth                                int64
spl_educator_yn                    int64
librarian_yn                       int64
land_avl_yn                        int64
kitchen_garden_yn                  int64
staff_qtr_yn                       int64
tinkering_lab_yn                   int64
boarding_pri_yn                    int64
boarding_upr_yn                    int64
boarding_sec_yn                    int64
boarding_hsec_yn                   int64
cyber_safety                       int64
psycho_social                      int64
enrichment_activities            float64
Sample:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,6773797,3,1,1,5,3,1,2,1,0,...,2,9,9,2,9,9,9,0,0,1.0
1,9214686,3,3,3,6,3,0,3,0,0,...,2,9,9,2,9,9,9,0,0,2.0
2,9525194,3,2,2,1,7,7,5,0,2,...,1,9,9,2,9,9,9,0,0,1.0

File: 20_tch.csv
Rows and columns: (44378, 38)
Column names: ['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
Data types:
pseudocode                                 int64
total_tch                                  int64
male                                       int64
female                                     int64
transgender                                int64
gen_tch                                    int64
sc_tch                                     int64
st_tch                                     int64
obc_tch                                    int64
regular                                    int64
contract                                   int64
part_time                                  int64
below_graduate                             int64
graduate                                   int64
post_graduate_and_above                    int64
trained_comp                               int64
class_taught_pr                            int64
class_taught_upr                           int64
class_taught_pr_upr                        int64
class_taught_sec_only                      int64
class_taught_hsec_only                     int64
class_taught_upr_sec                       int64
class_taught_sec_hsec                      int64
class_taugt_pre_primary_only               int64
class_taught_pr_and_pre_pri                int64
teacher_involve_non_training_assignment    int64
diploma_certificate                        int64
bachelor_of_ee                             int64
bed_equivalent                             int64
med_equivalent                             int64
other                                      int64
none                                       int64
diploma_special_edu                        int64
pursuing_rpc                               int64
diploma_ele_edu                            int64
early_childhood_tch                        int64
bed_nursery                                int64
trained_cwsn                               int64
Sample:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000233,2,1,1,0,0,1,0,1,1,...,0,0,2,0,0,0,0,0,0,0
1,1000320,2,1,1,0,0,0,1,1,1,...,0,0,1,0,0,0,0,1,0,0
2,1000390,2,1,1,0,0,0,1,1,0,...,0,0,1,0,0,0,0,0,0,0

============================================================
STATE: mp
============================================================

File: 23_prof1.csv
Rows and columns: (119694, 49)
Column names: ['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
Data types:
pseudocode                      int64
state                          object
district                       object
block                          object
rural_urban                     int64
lgd_urban_local_body_name      object
lgd_ward_name                  object
lgd_vill_name                  object
lgd_vill_panchayat_name        object
lgd_block_name                 object
school_category                 int64
school_type                     int64
lowclass                        int64
highclass                       int64
managment                       int64
pincode                         int64
special_school_for_cwsn         int64
shift_school                    int64
resi_school                     int64
resi_type                       int64
minority_school                 int64
medium_instr1                   int64
medium_of_instr2                int64
medium_of_instr3                int64
medium_of_instr4                int64
aff_board_sec                   int64
aff_board_hsec                  int64
approachable_road               int64
pre_primary                     int64
anganwadi_yn                    int64
avg_instr_days                  int64
cce_yn                          int64
same_sch_b                      int64
same_sch_g                      int64
other_sch_b                     int64
other_sch_g                     int64
anganwadi_ecce_b                int64
anganwadi_ecce_g                int64
cwsn_sch_type                   int64
rte_25p_admission_yn            int64
estd_year                       int64
certified_fit_india_yn          int64
is_nsqf                         int64
prevoc_yn                       int64
stc_yn                          int64
smdc_pta_yn                     int64
smdc_pta_meeting                int64
remedial_tch_enrol              int64
learner_holistic_rptcard_yn     int64
Sample:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,6437918,MADHYA PRADESH,KHANDWA,PANDHANA,1,NaN,NaN,Pangra,Pangra,Pandhana,...,9,2003,2,2,9,2,1,0,0,1
1,1622854,MADHYA PRADESH,ASHOKNAGAR,ASHOKNAGAR,1,NaN,NaN,Menai,Menai,Ashoknagar,...,9,2000,2,2,2,2,2,0,0,1
2,5688946,MADHYA PRADESH,INDORE,INDORE URBAN-2,2,Indore-Municipal Corporations,Khajaraana,NaN,NaN,NaN,...,9,2024,9,2,9,2,9,0,0,9

File: 23_fac.csv
Rows and columns: (119694, 82)
Column names: ['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
Data types:
pseudocode                         int64
building_status                    int64
no_building_blocks                 int64
pucca_building_blocks              int64
boundary_wall                      int64
total_class_rooms                  int64
other_rooms                        int64
classrooms_in_good_condition       int64
classrooms_needs_minor_repair      int64
classrooms_needs_major_repair      int64
separate_room_for_hm               int64
total_boys_toilet                  int64
total_boys_func_toilet             int64
total_girls_toilet                 int64
total_girls_func_toilet            int64
total_boys_cwsn_toilet             int64
func_boys_cwsn_friendly            int64
total_girls_cwsn_toilet            int64
func_girls_cwsn_friendly           int64
urinal_boys                        int64
urinal_girls                       int64
handwash_near_toilet               int64
hand_pump_yn                       int64
well_prot_yn                       int64
tap_yn                             int64
othsrc_yn                          int64
well_unprot_yn                     int64
pack_water_yn                      int64
hand_pump_fun_yn                   int64
well_prot_fun_yn                   int64
tap_fun_yn                         int64
othsrc_fun_yn                      int64
well_unprot_fun_yn                 int64
pack_water_fun_yn                  int64
rain_water_harvesting              int64
handwash_facility_for_meal         int64
electricity_availability           int64
solar_panel                        int64
library_availability               int64
book_bank                          int64
reading_corner                     int64
playground_available               int64
playground_alt_yn                  int64
medical_checkups                   int64
availability_ramps                 int64
availability_of_handrails          int64
furniture_availability             int64
phy_lab_cond                       int64
chem_lab_cond                      int64
bio_lab_cond                       int64
math_lab_cond                      int64
lang_lab_cond                      int64
geo_lab_cond                       int64
home_sc_lab_cond                   int64
psycho_lab_cond                    int64
comp_lab_cond                      int64
comp_ict_lab_yn                    int64
ict_lab_yn                         int64
laptop                             int64
tablet                             int64
desktop                            int64
digiboard                          int64
teachdev_tot                       int64
server_tot                         int64
smart_class_tv_tot                 int64
projector                          int64
printer                            int64
internet                           int64
dth                                int64
spl_educator_yn                    int64
librarian_yn                       int64
land_avl_yn                        int64
kitchen_garden_yn                  int64
staff_qtr_yn                       int64
tinkering_lab_yn                   int64
boarding_pri_yn                    int64
boarding_upr_yn                    int64
boarding_sec_yn                    int64
boarding_hsec_yn                   int64
cyber_safety                       int64
psycho_social                      int64
enrichment_activities            float64
Sample:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,3430331,3,1,1,5,3,0,1,2,0,...,2,9,9,2,9,9,9,0,0,1.0
1,5945458,3,3,3,1,3,0,1,1,1,...,2,9,9,2,9,9,9,0,0,1.0
2,3179225,3,1,1,1,1,0,1,0,0,...,2,9,9,2,9,9,9,0,0,1.0

File: 23_enr2.csv
Rows and columns: (1078230, 42)
Column names: ['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
Data types:
pseudocode    int64
item_group    int64
item_id       int64
cpp_b         int64
cpp_g         int64
cpp_t         int64
c1_b          int64
c1_g          int64
c1_t          int64
c2_b          int64
c2_g          int64
c2_t          int64
c3_b          int64
c3_g          int64
c3_t          int64
c4_b          int64
c4_g          int64
c4_t          int64
c5_b          int64
c5_g          int64
c5_t          int64
c6_b          int64
c6_g          int64
c6_t          int64
c7_b          int64
c7_g          int64
c7_t          int64
c8_b          int64
c8_g          int64
c8_t          int64
c9_b          int64
c9_g          int64
c9_t          int64
c10_b         int64
c10_g         int64
c10_t         int64
c11_b         int64
c11_g         int64
c11_t         int64
c12_b         int64
c12_g         int64
c12_t         int64
Sample:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000089,8,3,6,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000089,8,4,6,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1000089,8,5,4,2,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

File: 23_tch.csv
Rows and columns: (119694, 38)
Column names: ['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
Data types:
pseudocode                                 int64
total_tch                                  int64
male                                       int64
female                                     int64
transgender                                int64
gen_tch                                    int64
sc_tch                                     int64
st_tch                                     int64
obc_tch                                    int64
regular                                    int64
contract                                   int64
part_time                                  int64
below_graduate                             int64
graduate                                   int64
post_graduate_and_above                    int64
trained_comp                               int64
class_taught_pr                            int64
class_taught_upr                           int64
class_taught_pr_upr                        int64
class_taught_sec_only                      int64
class_taught_hsec_only                     int64
class_taught_upr_sec                       int64
class_taught_sec_hsec                      int64
class_taugt_pre_primary_only               int64
class_taught_pr_and_pre_pri                int64
teacher_involve_non_training_assignment    int64
diploma_certificate                        int64
bachelor_of_ee                             int64
bed_equivalent                             int64
med_equivalent                             int64
other                                      int64
none                                       int64
diploma_special_edu                        int64
pursuing_rpc                               int64
diploma_ele_edu                            int64
early_childhood_tch                        int64
bed_nursery                                int64
trained_cwsn                               int64
Sample:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000089,6,2,4,0,2,0,0,4,6,...,1,0,0,1,0,0,2,0,0,0
1,1000149,2,1,1,0,1,0,0,1,1,...,0,0,0,0,0,0,1,0,0,0
2,1000453,12,0,12,0,9,1,0,2,12,...,4,0,0,3,1,0,4,0,0,0

============================================================
STATE: bihar
============================================================

File: 10_prof1.csv
Rows and columns: (95285, 49)
Column names: ['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
Data types:
pseudocode                      int64
state                          object
district                       object
block                          object
rural_urban                     int64
lgd_urban_local_body_name      object
lgd_ward_name                  object
lgd_vill_name                  object
lgd_vill_panchayat_name        object
lgd_block_name                 object
school_category                 int64
school_type                     int64
lowclass                        int64
highclass                       int64
managment                       int64
pincode                         int64
special_school_for_cwsn         int64
shift_school                    int64
resi_school                     int64
resi_type                       int64
minority_school                 int64
medium_instr1                   int64
medium_of_instr2                int64
medium_of_instr3                int64
medium_of_instr4                int64
aff_board_sec                   int64
aff_board_hsec                  int64
approachable_road               int64
pre_primary                     int64
anganwadi_yn                    int64
avg_instr_days                  int64
cce_yn                          int64
same_sch_b                      int64
same_sch_g                      int64
other_sch_b                     int64
other_sch_g                     int64
anganwadi_ecce_b                int64
anganwadi_ecce_g                int64
cwsn_sch_type                   int64
rte_25p_admission_yn            int64
estd_year                       int64
certified_fit_india_yn          int64
is_nsqf                         int64
prevoc_yn                       int64
stc_yn                          int64
smdc_pta_yn                     int64
smdc_pta_meeting                int64
remedial_tch_enrol              int64
learner_holistic_rptcard_yn     int64
Sample:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,7626939,BIHAR,ROHTAS,TILOUTHU,1,NaN,NaN,Chorkap,Chandanpura,Tilouthu,...,9,1985,2,2,9,2,1,4,0,2
1,4739232,BIHAR,MADHUBANI,MADHEPUR,1,NaN,NaN,Sundar Birajit,Sundar Birajeet,Madhepur,...,9,1973,2,2,9,2,2,0,0,2
2,2400767,BIHAR,DARBHANGA,GHANSHYAMPUR,1,NaN,NaN,NaN,NaN,Ghanshyampur,...,9,1973,9,2,2,1,9,0,0,9

File: 10_tch.csv
Rows and columns: (95285, 38)
Column names: ['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
Data types:
pseudocode                                 int64
total_tch                                  int64
male                                       int64
female                                     int64
transgender                                int64
gen_tch                                    int64
sc_tch                                     int64
st_tch                                     int64
obc_tch                                    int64
regular                                    int64
contract                                   int64
part_time                                  int64
below_graduate                             int64
graduate                                   int64
post_graduate_and_above                    int64
trained_comp                               int64
class_taught_pr                            int64
class_taught_upr                           int64
class_taught_pr_upr                        int64
class_taught_sec_only                      int64
class_taught_hsec_only                     int64
class_taught_upr_sec                       int64
class_taught_sec_hsec                      int64
class_taugt_pre_primary_only               int64
class_taught_pr_and_pre_pri                int64
teacher_involve_non_training_assignment    int64
diploma_certificate                        int64
bachelor_of_ee                             int64
bed_equivalent                             int64
med_equivalent                             int64
other                                      int64
none                                       int64
diploma_special_edu                        int64
pursuing_rpc                               int64
diploma_ele_edu                            int64
early_childhood_tch                        int64
bed_nursery                                int64
trained_cwsn                               int64
Sample:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000031,13,9,4,0,4,1,0,8,13,...,4,1,1,3,1,0,0,0,0,0
1,1000035,8,6,2,0,2,2,0,4,8,...,7,1,0,0,0,0,0,0,0,0
2,1000049,4,1,3,0,0,0,0,4,4,...,0,0,0,0,0,0,0,0,0,0

File: 10_fac.csv
Rows and columns: (95285, 82)
Column names: ['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
Data types:
pseudocode                         int64
building_status                    int64
no_building_blocks                 int64
pucca_building_blocks              int64
boundary_wall                      int64
total_class_rooms                  int64
other_rooms                        int64
classrooms_in_good_condition       int64
classrooms_needs_minor_repair      int64
classrooms_needs_major_repair      int64
separate_room_for_hm               int64
total_boys_toilet                  int64
total_boys_func_toilet             int64
total_girls_toilet                 int64
total_girls_func_toilet            int64
total_boys_cwsn_toilet             int64
func_boys_cwsn_friendly            int64
total_girls_cwsn_toilet            int64
func_girls_cwsn_friendly           int64
urinal_boys                        int64
urinal_girls                       int64
handwash_near_toilet               int64
hand_pump_yn                       int64
well_prot_yn                       int64
tap_yn                             int64
othsrc_yn                          int64
well_unprot_yn                     int64
pack_water_yn                      int64
hand_pump_fun_yn                   int64
well_prot_fun_yn                   int64
tap_fun_yn                         int64
othsrc_fun_yn                      int64
well_unprot_fun_yn                 int64
pack_water_fun_yn                  int64
rain_water_harvesting              int64
handwash_facility_for_meal         int64
electricity_availability           int64
solar_panel                        int64
library_availability               int64
book_bank                          int64
reading_corner                     int64
playground_available               int64
playground_alt_yn                  int64
medical_checkups                   int64
availability_ramps                 int64
availability_of_handrails          int64
furniture_availability             int64
phy_lab_cond                       int64
chem_lab_cond                      int64
bio_lab_cond                       int64
math_lab_cond                      int64
lang_lab_cond                      int64
geo_lab_cond                       int64
home_sc_lab_cond                   int64
psycho_lab_cond                    int64
comp_lab_cond                      int64
comp_ict_lab_yn                    int64
ict_lab_yn                         int64
laptop                             int64
tablet                             int64
desktop                            int64
digiboard                          int64
teachdev_tot                       int64
server_tot                         int64
smart_class_tv_tot                 int64
projector                          int64
printer                            int64
internet                           int64
dth                                int64
spl_educator_yn                    int64
librarian_yn                       int64
land_avl_yn                        int64
kitchen_garden_yn                  int64
staff_qtr_yn                       int64
tinkering_lab_yn                   int64
boarding_pri_yn                    int64
boarding_upr_yn                    int64
boarding_sec_yn                    int64
boarding_hsec_yn                   int64
cyber_safety                       int64
psycho_social                      int64
enrichment_activities            float64
Sample:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,6459768,3,3,3,1,8,0,5,3,0,...,2,9,9,2,9,9,9,0,0,1.0
1,6772401,3,2,2,1,8,0,4,4,0,...,2,9,9,2,9,9,9,0,0,1.0
2,7863767,4,1,1,1,1,0,1,0,0,...,2,9,9,2,9,9,9,0,0,1.0

File: 10_enr2.csv
Rows and columns: (972166, 42)
Column names: ['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
Data types:
pseudocode    int64
item_group    int64
item_id       int64
cpp_b         int64
cpp_g         int64
cpp_t         int64
c1_b          int64
c1_g          int64
c1_t          int64
c2_b          int64
c2_g          int64
c2_t          int64
c3_b          int64
c3_g          int64
c3_t          int64
c4_b          int64
c4_g          int64
c4_t          int64
c5_b          int64
c5_g          int64
c5_t          int64
c6_b          int64
c6_g          int64
c6_t          int64
c7_b          int64
c7_g          int64
c7_t          int64
c8_b          int64
c8_g          int64
c8_t          int64
c9_b          int64
c9_g          int64
c9_t          int64
c10_b         int64
c10_g         int64
c10_t         int64
c11_b         int64
c11_g         int64
c11_t         int64
c12_b         int64
c12_g         int64
c12_t         int64
Sample:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000031,8,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000031,8,5,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1000031,8,6,0,0,0,4,7,0,0,...,0,0,0,0,0,0,0,0,0,0

============================================================
STATE: rajasthan
============================================================

File: 08_tch.csv
Rows and columns: (106445, 38)
Column names: ['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
Data types:
pseudocode                                 int64
total_tch                                  int64
male                                       int64
female                                     int64
transgender                                int64
gen_tch                                    int64
sc_tch                                     int64
st_tch                                     int64
obc_tch                                    int64
regular                                    int64
contract                                   int64
part_time                                  int64
below_graduate                             int64
graduate                                   int64
post_graduate_and_above                    int64
trained_comp                               int64
class_taught_pr                            int64
class_taught_upr                           int64
class_taught_pr_upr                        int64
class_taught_sec_only                      int64
class_taught_hsec_only                     int64
class_taught_upr_sec                       int64
class_taught_sec_hsec                      int64
class_taugt_pre_primary_only               int64
class_taught_pr_and_pre_pri                int64
teacher_involve_non_training_assignment    int64
diploma_certificate                        int64
bachelor_of_ee                             int64
bed_equivalent                             int64
med_equivalent                             int64
other                                      int64
none                                       int64
diploma_special_edu                        int64
pursuing_rpc                               int64
diploma_ele_edu                            int64
early_childhood_tch                        int64
bed_nursery                                int64
trained_cwsn                               int64
Sample:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000032,2,1,1,0,0,1,0,1,2,...,0,0,0,0,0,0,0,0,0,0
1,1000150,3,1,2,0,0,1,0,2,2,...,1,0,0,2,0,0,0,0,0,0
2,1000199,4,4,0,0,0,2,0,2,4,...,0,0,1,3,0,0,0,0,0,0

File: 08_enr2.csv
Rows and columns: (1084857, 42)
Column names: ['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
Data types:
pseudocode    int64
item_group    int64
item_id       int64
cpp_b         int64
cpp_g         int64
cpp_t         int64
c1_b          int64
c1_g          int64
c1_t          int64
c2_b          int64
c2_g          int64
c2_t          int64
c3_b          int64
c3_g          int64
c3_t          int64
c4_b          int64
c4_g          int64
c4_t          int64
c5_b          int64
c5_g          int64
c5_t          int64
c6_b          int64
c6_g          int64
c6_t          int64
c7_b          int64
c7_g          int64
c7_t          int64
c8_b          int64
c8_g          int64
c8_t          int64
c9_b          int64
c9_g          int64
c9_t          int64
c10_b         int64
c10_g         int64
c10_t         int64
c11_b         int64
c11_g         int64
c11_t         int64
c12_b         int64
c12_g         int64
c12_t         int64
Sample:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000032,8,4,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000032,8,5,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1000032,8,6,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

File: 08_prof1.csv
Rows and columns: (106445, 49)
Column names: ['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
Data types:
pseudocode                      int64
state                          object
district                       object
block                          object
rural_urban                     int64
lgd_urban_local_body_name      object
lgd_ward_name                  object
lgd_vill_name                  object
lgd_vill_panchayat_name        object
lgd_block_name                 object
school_category                 int64
school_type                     int64
lowclass                        int64
highclass                       int64
managment                       int64
pincode                         int64
special_school_for_cwsn         int64
shift_school                    int64
resi_school                     int64
resi_type                       int64
minority_school                 int64
medium_instr1                   int64
medium_of_instr2                int64
medium_of_instr3                int64
medium_of_instr4                int64
aff_board_sec                   int64
aff_board_hsec                  int64
approachable_road               int64
pre_primary                     int64
anganwadi_yn                    int64
avg_instr_days                  int64
cce_yn                          int64
same_sch_b                      int64
same_sch_g                      int64
other_sch_b                     int64
other_sch_g                     int64
anganwadi_ecce_b                int64
anganwadi_ecce_g                int64
cwsn_sch_type                   int64
rte_25p_admission_yn            int64
estd_year                       int64
certified_fit_india_yn          int64
is_nsqf                         int64
prevoc_yn                       int64
stc_yn                          int64
smdc_pta_yn                     int64
smdc_pta_meeting                int64
remedial_tch_enrol              int64
learner_holistic_rptcard_yn     int64
Sample:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,8131457,RAJASTHAN,PHALODI,BAPINI,1,NaN,NaN,Motaniya Nagar,Motaniya Nagar,Bapini,...,9,1999,1,2,9,2,1,0,0,2
1,4842002,RAJASTHAN,BALOTRA,GIDA,1,NaN,NaN,Kharthoniyon Ka Tala,Kanor,Gira,...,9,1995,1,2,2,2,1,2,0,1
2,4718146,RAJASTHAN,PRATAPGARH,PRATAPGARH,1,NaN,NaN,Awleshwar,Awleshwar,Pratapgarh,...,9,1932,1,1,2,2,1,4,0,1

File: 08_fac.csv
Rows and columns: (106445, 82)
Column names: ['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
Data types:
pseudocode                         int64
building_status                    int64
no_building_blocks                 int64
pucca_building_blocks              int64
boundary_wall                      int64
total_class_rooms                  int64
other_rooms                        int64
classrooms_in_good_condition       int64
classrooms_needs_minor_repair      int64
classrooms_needs_major_repair      int64
separate_room_for_hm               int64
total_boys_toilet                  int64
total_boys_func_toilet             int64
total_girls_toilet                 int64
total_girls_func_toilet            int64
total_boys_cwsn_toilet             int64
func_boys_cwsn_friendly            int64
total_girls_cwsn_toilet            int64
func_girls_cwsn_friendly           int64
urinal_boys                        int64
urinal_girls                       int64
handwash_near_toilet               int64
hand_pump_yn                       int64
well_prot_yn                       int64
tap_yn                             int64
othsrc_yn                          int64
well_unprot_yn                     int64
pack_water_yn                      int64
hand_pump_fun_yn                   int64
well_prot_fun_yn                   int64
tap_fun_yn                         int64
othsrc_fun_yn                      int64
well_unprot_fun_yn                 int64
pack_water_fun_yn                  int64
rain_water_harvesting              int64
handwash_facility_for_meal         int64
electricity_availability           int64
solar_panel                        int64
library_availability               int64
book_bank                          int64
reading_corner                     int64
playground_available               int64
playground_alt_yn                  int64
medical_checkups                   int64
availability_ramps                 int64
availability_of_handrails          int64
furniture_availability             int64
phy_lab_cond                       int64
chem_lab_cond                      int64
bio_lab_cond                       int64
math_lab_cond                      int64
lang_lab_cond                      int64
geo_lab_cond                       int64
home_sc_lab_cond                   int64
psycho_lab_cond                    int64
comp_lab_cond                      int64
comp_ict_lab_yn                    int64
ict_lab_yn                         int64
laptop                             int64
tablet                             int64
desktop                            int64
digiboard                          int64
teachdev_tot                       int64
server_tot                         int64
smart_class_tv_tot                 int64
projector                          int64
printer                            int64
internet                           int64
dth                                int64
spl_educator_yn                    int64
librarian_yn                       int64
land_avl_yn                        int64
kitchen_garden_yn                  int64
staff_qtr_yn                       int64
tinkering_lab_yn                   int64
boarding_pri_yn                    int64
boarding_upr_yn                    int64
boarding_sec_yn                    int64
boarding_hsec_yn                   int64
cyber_safety                       int64
psycho_social                      int64
enrichment_activities            float64
Sample:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,3131252,3,1,1,6,2,1,2,0,0,...,2,9,9,2,9,9,9,0,0,1.0
1,5085949,3,1,1,1,3,3,1,0,2,...,2,9,9,2,9,9,9,0,0,1.0
2,4842002,3,1,1,3,5,5,5,0,0,...,2,9,9,2,9,9,9,111,0,1.0

============================================================
STATE: haryana
============================================================

File: 06_fac.csv
Rows and columns: (23479, 82)
Column names: ['pseudocode', 'building_status', 'no_building_blocks', 'pucca_building_blocks', 'boundary_wall', 'total_class_rooms', 'other_rooms', 'classrooms_in_good_condition', 'classrooms_needs_minor_repair', 'classrooms_needs_major_repair', 'separate_room_for_hm', 'total_boys_toilet', 'total_boys_func_toilet', 'total_girls_toilet', 'total_girls_func_toilet', 'total_boys_cwsn_toilet', 'func_boys_cwsn_friendly', 'total_girls_cwsn_toilet', 'func_girls_cwsn_friendly', 'urinal_boys', 'urinal_girls', 'handwash_near_toilet', 'hand_pump_yn', 'well_prot_yn', 'tap_yn', 'othsrc_yn', 'well_unprot_yn', 'pack_water_yn', 'hand_pump_fun_yn', 'well_prot_fun_yn', 'tap_fun_yn', 'othsrc_fun_yn', 'well_unprot_fun_yn', 'pack_water_fun_yn', 'rain_water_harvesting', 'handwash_facility_for_meal', 'electricity_availability', 'solar_panel', 'library_availability', 'book_bank', 'reading_corner', 'playground_available', 'playground_alt_yn', 'medical_checkups', 'availability_ramps', 'availability_of_handrails', 'furniture_availability', 'phy_lab_cond', 'chem_lab_cond', 'bio_lab_cond', 'math_lab_cond', 'lang_lab_cond', 'geo_lab_cond', 'home_sc_lab_cond', 'psycho_lab_cond', 'comp_lab_cond', 'comp_ict_lab_yn', 'ict_lab_yn', 'laptop', 'tablet', 'desktop', 'digiboard', 'teachdev_tot', 'server_tot', 'smart_class_tv_tot', 'projector', 'printer', 'internet', 'dth', 'spl_educator_yn', 'librarian_yn', 'land_avl_yn', 'kitchen_garden_yn', 'staff_qtr_yn', 'tinkering_lab_yn', 'boarding_pri_yn', 'boarding_upr_yn', 'boarding_sec_yn', 'boarding_hsec_yn', 'cyber_safety', 'psycho_social', 'enrichment_activities']
Data types:
pseudocode                         int64
building_status                    int64
no_building_blocks                 int64
pucca_building_blocks              int64
boundary_wall                      int64
total_class_rooms                  int64
other_rooms                        int64
classrooms_in_good_condition       int64
classrooms_needs_minor_repair      int64
classrooms_needs_major_repair      int64
separate_room_for_hm               int64
total_boys_toilet                  int64
total_boys_func_toilet             int64
total_girls_toilet                 int64
total_girls_func_toilet            int64
total_boys_cwsn_toilet             int64
func_boys_cwsn_friendly            int64
total_girls_cwsn_toilet            int64
func_girls_cwsn_friendly           int64
urinal_boys                        int64
urinal_girls                       int64
handwash_near_toilet               int64
hand_pump_yn                       int64
well_prot_yn                       int64
tap_yn                             int64
othsrc_yn                          int64
well_unprot_yn                     int64
pack_water_yn                      int64
hand_pump_fun_yn                   int64
well_prot_fun_yn                   int64
tap_fun_yn                         int64
othsrc_fun_yn                      int64
well_unprot_fun_yn                 int64
pack_water_fun_yn                  int64
rain_water_harvesting              int64
handwash_facility_for_meal         int64
electricity_availability           int64
solar_panel                        int64
library_availability               int64
book_bank                          int64
reading_corner                     int64
playground_available               int64
playground_alt_yn                  int64
medical_checkups                   int64
availability_ramps                 int64
availability_of_handrails          int64
furniture_availability             int64
phy_lab_cond                       int64
chem_lab_cond                      int64
bio_lab_cond                       int64
math_lab_cond                      int64
lang_lab_cond                      int64
geo_lab_cond                       int64
home_sc_lab_cond                   int64
psycho_lab_cond                    int64
comp_lab_cond                      int64
comp_ict_lab_yn                    int64
ict_lab_yn                         int64
laptop                             int64
tablet                             int64
desktop                            int64
digiboard                          int64
teachdev_tot                       int64
server_tot                         int64
smart_class_tv_tot                 int64
projector                          int64
printer                            int64
internet                           int64
dth                                int64
spl_educator_yn                    int64
librarian_yn                       int64
land_avl_yn                        int64
kitchen_garden_yn                  int64
staff_qtr_yn                       int64
tinkering_lab_yn                   int64
boarding_pri_yn                    int64
boarding_upr_yn                    int64
boarding_sec_yn                    int64
boarding_hsec_yn                   int64
cyber_safety                       int64
psycho_social                      int64
enrichment_activities            float64
Sample:

,pseudocode,building_status,no_building_blocks,pucca_building_blocks,boundary_wall,total_class_rooms,other_rooms,classrooms_in_good_condition,classrooms_needs_minor_repair,classrooms_needs_major_repair,...,kitchen_garden_yn,staff_qtr_yn,tinkering_lab_yn,boarding_pri_yn,boarding_upr_yn,boarding_sec_yn,boarding_hsec_yn,cyber_safety,psycho_social,enrichment_activities
0,3866044,3,1,1,1,6,2,3,3,0,...,1,9,9,2,9,9,9,0,0,1.0
1,5253916,3,7,7,1,11,8,4,7,0,...,1,2,2,9,9,2,2,171,171,1.0
2,4592997,3,1,1,1,14,7,7,4,3,...,1,2,2,9,9,2,2,653,653,1.0

File: 06_enr2.csv
Rows and columns: (240115, 42)
Column names: ['pseudocode', 'item_group', 'item_id', 'cpp_b', 'cpp_g', 'cpp_t', 'c1_b', 'c1_g', 'c1_t', 'c2_b', 'c2_g', 'c2_t', 'c3_b', 'c3_g', 'c3_t', 'c4_b', 'c4_g', 'c4_t', 'c5_b', 'c5_g', 'c5_t', 'c6_b', 'c6_g', 'c6_t', 'c7_b', 'c7_g', 'c7_t', 'c8_b', 'c8_g', 'c8_t', 'c9_b', 'c9_g', 'c9_t', 'c10_b', 'c10_g', 'c10_t', 'c11_b', 'c11_g', 'c11_t', 'c12_b', 'c12_g', 'c12_t']
Data types:
pseudocode    int64
item_group    int64
item_id       int64
cpp_b         int64
cpp_g         int64
cpp_t         int64
c1_b          int64
c1_g          int64
c1_t          int64
c2_b          int64
c2_g          int64
c2_t          int64
c3_b          int64
c3_g          int64
c3_t          int64
c4_b          int64
c4_g          int64
c4_t          int64
c5_b          int64
c5_g          int64
c5_t          int64
c6_b          int64
c6_g          int64
c6_t          int64
c7_b          int64
c7_g          int64
c7_t          int64
c8_b          int64
c8_g          int64
c8_t          int64
c9_b          int64
c9_g          int64
c9_t          int64
c10_b         int64
c10_g         int64
c10_t         int64
c11_b         int64
c11_g         int64
c11_t         int64
c12_b         int64
c12_g         int64
c12_t         int64
Sample:

,pseudocode,item_group,item_id,cpp_b,cpp_g,cpp_t,c1_b,c1_g,c1_t,c2_b,...,c9_t,c10_b,c10_g,c10_t,c11_b,c11_g,c11_t,c12_b,c12_g,c12_t
0,1000040,8,4,0,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000040,8,5,4,1,0,5,5,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1000040,8,6,1,0,0,3,8,0,6,...,0,0,0,0,0,0,0,0,0,0

File: 06_tch.csv
Rows and columns: (23479, 38)
Column names: ['pseudocode', 'total_tch', 'male', 'female', 'transgender', 'gen_tch', 'sc_tch', 'st_tch', 'obc_tch', 'regular', 'contract', 'part_time', 'below_graduate', 'graduate', 'post_graduate_and_above', 'trained_comp', 'class_taught_pr', 'class_taught_upr', 'class_taught_pr_upr', 'class_taught_sec_only', 'class_taught_hsec_only', 'class_taught_upr_sec', 'class_taught_sec_hsec', 'class_taugt_pre_primary_only', 'class_taught_pr_and_pre_pri', 'teacher_involve_non_training_assignment', 'diploma_certificate', 'bachelor_of_ee', 'bed_equivalent', 'med_equivalent', 'other', 'none', 'diploma_special_edu', 'pursuing_rpc', 'diploma_ele_edu', 'early_childhood_tch', 'bed_nursery', 'trained_cwsn']
Data types:
pseudocode                                 int64
total_tch                                  int64
male                                       int64
female                                     int64
transgender                                int64
gen_tch                                    int64
sc_tch                                     int64
st_tch                                     int64
obc_tch                                    int64
regular                                    int64
contract                                   int64
part_time                                  int64
below_graduate                             int64
graduate                                   int64
post_graduate_and_above                    int64
trained_comp                               int64
class_taught_pr                            int64
class_taught_upr                           int64
class_taught_pr_upr                        int64
class_taught_sec_only                      int64
class_taught_hsec_only                     int64
class_taught_upr_sec                       int64
class_taught_sec_hsec                      int64
class_taugt_pre_primary_only               int64
class_taught_pr_and_pre_pri                int64
teacher_involve_non_training_assignment    int64
diploma_certificate                        int64
bachelor_of_ee                             int64
bed_equivalent                             int64
med_equivalent                             int64
other                                      int64
none                                       int64
diploma_special_edu                        int64
pursuing_rpc                               int64
diploma_ele_edu                            int64
early_childhood_tch                        int64
bed_nursery                                int64
trained_cwsn                               int64
Sample:

,pseudocode,total_tch,male,female,transgender,gen_tch,sc_tch,st_tch,obc_tch,regular,...,bed_equivalent,med_equivalent,other,none,diploma_special_edu,pursuing_rpc,diploma_ele_edu,early_childhood_tch,bed_nursery,trained_cwsn
0,1000040,13,5,8,0,6,3,0,4,2,...,4,0,3,3,0,0,1,0,0,0
1,1001720,16,6,10,0,8,0,0,8,0,...,11,0,0,1,0,0,0,0,0,0
2,1002230,5,0,5,0,4,0,0,1,0,...,3,0,1,0,0,0,1,0,0,0

File: 06_prof1.csv
Rows and columns: (23479, 49)
Column names: ['pseudocode', 'state', 'district', 'block', 'rural_urban', 'lgd_urban_local_body_name', 'lgd_ward_name', 'lgd_vill_name', 'lgd_vill_panchayat_name', 'lgd_block_name', 'school_category', 'school_type', 'lowclass', 'highclass', 'managment', 'pincode', 'special_school_for_cwsn', 'shift_school', 'resi_school', 'resi_type', 'minority_school', 'medium_instr1', 'medium_of_instr2', 'medium_of_instr3', 'medium_of_instr4', 'aff_board_sec', 'aff_board_hsec', 'approachable_road', 'pre_primary', 'anganwadi_yn', 'avg_instr_days', 'cce_yn', 'same_sch_b', 'same_sch_g', 'other_sch_b', 'other_sch_g', 'anganwadi_ecce_b', 'anganwadi_ecce_g', 'cwsn_sch_type', 'rte_25p_admission_yn', 'estd_year', 'certified_fit_india_yn', 'is_nsqf', 'prevoc_yn', 'stc_yn', 'smdc_pta_yn', 'smdc_pta_meeting', 'remedial_tch_enrol', 'learner_holistic_rptcard_yn']
Data types:
pseudocode                      int64
state                          object
district                       object
block                          object
rural_urban                     int64
lgd_urban_local_body_name      object
lgd_ward_name                  object
lgd_vill_name                  object
lgd_vill_panchayat_name        object
lgd_block_name                 object
school_category                 int64
school_type                     int64
lowclass                        int64
highclass                       int64
managment                       int64
pincode                         int64
special_school_for_cwsn         int64
shift_school                    int64
resi_school                     int64
resi_type                       int64
minority_school                 int64
medium_instr1                   int64
medium_of_instr2                int64
medium_of_instr3                int64
medium_of_instr4                int64
aff_board_sec                   int64
aff_board_hsec                  int64
approachable_road               int64
pre_primary                     int64
anganwadi_yn                    int64
avg_instr_days                  int64
cce_yn                          int64
same_sch_b                      int64
same_sch_g                      int64
other_sch_b                     int64
other_sch_g                     int64
anganwadi_ecce_b                int64
anganwadi_ecce_g                int64
cwsn_sch_type                   int64
rte_25p_admission_yn            int64
estd_year                       int64
certified_fit_india_yn          int64
is_nsqf                         int64
prevoc_yn                       int64
stc_yn                          int64
smdc_pta_yn                     int64
smdc_pta_meeting                int64
remedial_tch_enrol              int64
learner_holistic_rptcard_yn     int64
Sample:

,pseudocode,state,district,block,rural_urban,lgd_urban_local_body_name,lgd_ward_name,lgd_vill_name,lgd_vill_panchayat_name,lgd_block_name,...,rte_25p_admission_yn,estd_year,certified_fit_india_yn,is_nsqf,prevoc_yn,stc_yn,smdc_pta_yn,smdc_pta_meeting,remedial_tch_enrol,learner_holistic_rptcard_yn
0,5864327,HARYANA,NUH,PUNHANA,1,NaN,NaN,Hathan Gaon(227),Hathangaon,Punahana,...,9,1954,1,2,9,2,1,9,0,1
1,9234276,HARYANA,YAMUNANAGAR,CHHACHHRAULI,1,NaN,NaN,Chhachhrauli (311),Chhachhrauli,Chhachhrauli,...,9,1960,2,2,9,2,2,0,0,2
2,1753236,HARYANA,JIND,SAFIDON,1,NaN,NaN,Jaipur (24),Jaipur,Safidon,...,9,1956,2,2,9,2,1,10,0,1